const SHOP_DATA_REDUCER_ACTION_TYPES = {
  UPDATE_FASHION_COLLECTION_PREVIEW_DATA:
    'UPDATE_FASHION_COLLECTION_PREVIEW_DATA',
  FETCH_FASHION_COLLECTION_START: 'FETCH_FASHION_COLLECTION_START',
  FETCH_FASHION_COLLECTION_SUCCESS: 'FETCH_FASHION_COLLECTION_SUCCESS',
  FETCH_FASHION_COLLECTION_FAILURE: 'FETCH_FASHION_COLLECTION_FAILURE',
};

export default SHOP_DATA_REDUCER_ACTION_TYPES;
